version: "3.8"

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - my_postgres  # PostgreSQL servisi
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: myredis
    ports:
      - "6379:6379"
    networks:
      - backend

  my_postgres:
    image: postgres:latest
    container_name: mypostgres
    environment:
      POSTGRES_DB: backend_db    # Veritabanı adı
      POSTGRES_USER: user        # Kullanıcı adı
      POSTGRES_PASSWORD: asdqwe123 # Şifre
    ports:
      - "5432:5432"             # PostgreSQL portu
    networks:
      - backend

networks:
  backend:
    driver: bridge
