# Generated by Django 5.1.3 on 2024-11-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='worked_hours',
            field=models.FloatField(default=0),
        ),
    ]
