# Generated by Django 5.1.3 on 2024-11-25 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_attendance_exit_time_attendance_worked_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandı', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='beklemede', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='expected_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
